### PR TITLE
Added dep/department 

### PR DESCRIPTION
**Pull request by Jeevz10**

### CODE REVIEW

**Comment by jieliangang** [comment]
Under seedu.address.ui.MainWindow, 

browserPlaceholder.getChildren().add(browserPanel.getRoot());

gui tests have not been updated thats why travis failed

**Comment by IcedCoffeeBoy** [comment]
Check style errors:
1) java/seedu/address/logic/commands/EditCommand.java:202:53: '{' at column 53 should have line break after. [LeftCurly]
2) java/seedu/address/model/person/Person.java:63:39: '{' at column 39 should have line break after. [LeftCurly]
3)

**Comment by IcedCoffeeBoy** [comment]
> Under seedu.address.ui.MainWindow,
> 
> browserPlaceholder.getChildren().add(browserPanel.getRoot());
> 
> gui tests have not been updated thats why travis failed

Seems to me Jeevan have reverted the changes on the GUI. Error may come from other sources.

**Comment by Jeevz10** [comment]
i understand what went wrong. My bad. Working on it now.

**Pull request merged**
